### ISSUE TITLE
Trigger: Window shown

### ISSUE THREAD

**Issue by vegardlarsen** [digitalcreations/MaxTo#702]
**Describe the solution you'd like**
It should be possible to trigger recipes based on when windows are shown or hidden. "Window opened" (which should really be "Window created") does not trigger if the window is created hidden and then shown later.

**Additional context**
E.g. Notepad does not trigger the "Window opened" trigger today, as the window is created invisible, and then shown later.

**Comment by vegardlarsen** [comment]
I have implemented a new "Window shown" trigger, which works well. I elected not to do the same for "Window hidden", as I can't really see the use case after thinking it through.

**Comment by xairoo** [comment]
Doesn't seem to work @ 2.2.0.

Tried it with `windowsterminal*`, works.
`windowsterminal.exe` didn't worked.

Also using titles like `Window PowerShell` and so on didn't worked.

Staring a windows terminal worked to trigger the recipe for a few times. Then it stopped.
Now it won't get triggered anymore.

I also launch a few terminals using a simple batch script. The first terminal will benefit from the recipe (move). The others won't.
Now nothing happens. Restarting MaxTo didn't helped.

```json
{
  "enabled": true,
  "name": "terminal auto resize",
  "id": null,
  "triggers": [
    {
      "type": "window:shown",
      "Window": "\\windowsterminal*\\\\"
    }
  ],
  "ingredients": [
    {
      "command": "window:move",
      "parameters": {
        "region": "95%,50%",
        "window": "\\\\\\"
      }
    }
  ]
}
```

**Comment by vegardlarsen** [comment]
Hi there, when trying to reproduce this in version 2.2.1; the following recipe works:

```json
{
  "enabled": true,
  "name": "Auto-resize Terminal",
  "id": null,
  "triggers": [
    {
      "type": "window:shown",
      "Window": "\\WindowsTerminal\\\\"
    }
  ],
  "ingredients": [
    {
      "command": "window:move",
      "parameters": {
        "region": "center left"
      }
    }
  ]
}
```

The only real difference I can see to your recipe, is that I've removed the window parameter to the command.

**Comment by xairoo** [comment]
Currently using this and it's working too:

```
{
  "enabled": true,
  "name": "autoplace wt",
  "id": null,
  "triggers": [
    {
      "type": "window:shown",
      "Window": "\\\\CASCADIA_HOSTING_WINDOW_CLASS\\"
    }
  ],
  "ingredients": [
    {
      "command": "window:move",
      "parameters": {
        "window": "\\\\CASCADIA_HOSTING_WINDOW_CLASS\\",
        "region": "90%,0"
      }
    }
  ]
}
```

Your recipe works too.

But the problem still exists if you start multiple terminals using a batch script (guess that will happen with all programs):
```
start wt.exe -d .
timeout /t 1
start wt.exe -d .
timeout /t 1
start wt.exe -d .
timeout /t 1
start wt.exe -d .
```

But... message "prevent infinite loops" get's fired.
Timeout has to be 2 seconds to prevent this notice.
Also sometimes the window gets resized - although the notices comes up.
No chance to get all windows resized without the timeout.

**Comment by vegardlarsen** [comment]
Thanks for the feedback on this. The infinite loops message is a bit annoying, but necessary. It shouldn't trigger in your case though, as it should allow 10 executions before triggering (you are spot on with the timeout, though, it is 2 seconds).

If you can reliably reproduce this with the above recipe and batch scripts, let me know, and I will take a closer look.
